config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resource :books, except: [:edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
     def self.get_data_from_api
        response = RestClient.get("https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=#{ENV['BOOK_KEY']}")
        books_array = JSON.parse(response)["results"]["books"]
        books_array.each do |book|
            self.create(rank: book["rank"] , title: book["title"], author: book["author"], description: book["description"])
        end 
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def welcome
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    
    def show
        @books = Book.find_by(id: params[:id])
    end

    def new
        @books = Book.new
    end
    
    def create
        @books = Book.new(book_params)
        if @books.save
            redirect_to root_path, notice: "Book added successfully"
        else
            render :new
        end
    end

    def destroy
        @book = Book.find(params[:id])
        if @book.destroy
            redirect_to root_path, notice: "Book removed sucessfully."
        else
            redirect_to root_path, notice: "Faced issue while deleting."
        end
    end

    private
    def book_params
        params.require(:book).permit(:rank, :title, :author, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end%>    
<table >
    <tr>
        <td>Rank</td>
        <td>Title</td>
        <td>Author</td>
        <td>Descrption</td>  
    </tr>
    <% @books.each do |b|%>
    <tr>
        <td><%= b.rank %></td>
        <td><%= b.title %></td>
        <td><%= b.author %></td>
    <td><%= truncate(b.description) %></td></tr>
    <%end%>
</table>
<%= link_to "Add Book", new_books_path %>

app/views/books/new.html.erb
<%= form_with model: @books do |f| %>
    Rank: <%= f.text_field :rank %>
    Title: <%= f.text_field :title %>
    Author: <%= f.text_field :author %>
    Description: <%= f.text_field :description %>
    <%= f.submit 'Add Book' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>